# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dadosCliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formDadosCliente(object):
    def setupUi(self, formDadosCliente):
        formDadosCliente.setObjectName("formDadosCliente")
        formDadosCliente.resize(335, 187)
        self.LBL_nome = QtWidgets.QLabel(formDadosCliente)
        self.LBL_nome.setGeometry(QtCore.QRect(10, 20, 47, 13))
        self.LBL_nome.setObjectName("LBL_nome")
        self.LE_nome = QtWidgets.QLineEdit(formDadosCliente)
        self.LE_nome.setGeometry(QtCore.QRect(60, 20, 261, 16))
        self.LE_nome.setObjectName("LE_nome")
        self.LE_telefone = QtWidgets.QLineEdit(formDadosCliente)
        self.LE_telefone.setGeometry(QtCore.QRect(60, 50, 261, 16))
        self.LE_telefone.setObjectName("LE_telefone")
        self.LBL_telefone = QtWidgets.QLabel(formDadosCliente)
        self.LBL_telefone.setGeometry(QtCore.QRect(10, 50, 47, 13))
        self.LBL_telefone.setObjectName("LBL_telefone")
        self.LE_cidade = QtWidgets.QLineEdit(formDadosCliente)
        self.LE_cidade.setGeometry(QtCore.QRect(60, 80, 261, 16))
        self.LE_cidade.setObjectName("LE_cidade")
        self.LBL_cidade = QtWidgets.QLabel(formDadosCliente)
        self.LBL_cidade.setGeometry(QtCore.QRect(10, 80, 47, 13))
        self.LBL_cidade.setObjectName("LBL_cidade")
        self.BT_cancelar = QtWidgets.QPushButton(formDadosCliente)
        self.BT_cancelar.setGeometry(QtCore.QRect(10, 110, 81, 71))
        self.BT_cancelar.setStyleSheet("image:url(:/icon_cancelar/icons/cancelar.png)")
        self.BT_cancelar.setText("")
        self.BT_cancelar.setObjectName("BT_cancelar")
        self.BT_cadastrar = QtWidgets.QPushButton(formDadosCliente)
        self.BT_cadastrar.setGeometry(QtCore.QRect(240, 110, 81, 71))
        self.BT_cadastrar.setStyleSheet("image:url(:/icon_cadastrar/icons/cadastrar.png)")
        self.BT_cadastrar.setText("")
        self.BT_cadastrar.setObjectName("BT_cadastrar")

        self.retranslateUi(formDadosCliente)
        QtCore.QMetaObject.connectSlotsByName(formDadosCliente)

    def retranslateUi(self, formDadosCliente):
        _translate = QtCore.QCoreApplication.translate
        formDadosCliente.setWindowTitle(_translate("formDadosCliente", "Form"))
        self.LBL_nome.setText(_translate("formDadosCliente", "Nome:"))
        self.LBL_telefone.setText(_translate("formDadosCliente", "Telefone:"))
        self.LBL_cidade.setText(_translate("formDadosCliente", "Cidade:"))
import icon_cadastrar_rc
import icon_cancelar_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formDadosCliente = QtWidgets.QWidget()
    ui = Ui_formDadosCliente()
    ui.setupUi(formDadosCliente)
    formDadosCliente.show()
    sys.exit(app.exec_())
